## 1. 스키마 생성
CREATE DATABASE IF NOT EXISTS community;
USE community;

## 2. user 테이블 생성
CREATE TABLE user (
user_id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
email VARCHAR(255) NOT NULL UNIQUE,
password VARCHAR(255) NOT NULL,
username VARCHAR(100) NOT NULL,
image VARCHAR(255) NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NULL,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP
);

## 3. post 테이블 생성
CREATE TABLE post (
post_id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
user_id INT UNSIGNED NOT NULL,
title VARCHAR(255) NOT NULL,
content TEXT NOT NULL,
image VARCHAR(255) NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NULL,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP,
views INT UNSIGNED DEFAULT 0 NULL,
CONSTRAINT post_ibfk_1 FOREIGN KEY (user_id) REFERENCES user (user_id) ON DELETE CASCADE
);

## 4. comment 테이블 생성
CREATE TABLE comment (
comment_id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
post_id INT UNSIGNED NOT NULL,
user_id INT UNSIGNED NOT NULL,
content TEXT NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NULL,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP,
CONSTRAINT comment_ibfk_1 FOREIGN KEY (post_id) REFERENCES post (post_id) ON DELETE CASCADE,
CONSTRAINT comment_ibfk_2 FOREIGN KEY (user_id) REFERENCES user (user_id) ON DELETE CASCADE
);

## 5. 인덱스 생성
CREATE INDEX post_id ON comment (post_id);
CREATE INDEX user_id ON comment (user_id);

## 6. like 테이블 생성
CREATE TABLE `like` (
like_id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
post_id INT UNSIGNED NOT NULL,
user_id INT UNSIGNED NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NULL,
CONSTRAINT post_id UNIQUE (post_id, user_id),
CONSTRAINT like_ibfk_1 FOREIGN KEY (post_id) REFERENCES post (post_id) ON DELETE CASCADE,
CONSTRAINT like_ibfk_2 FOREIGN KEY (user_id) REFERENCES user (user_id) ON DELETE CASCADE
);

## 7. 인덱스 생성
CREATE INDEX user_id ON `like` (user_id);
CREATE INDEX user_id ON post (user_id);
